### ISSUE TITLE
Umbrella Issue to components and required docs to increase community standards

### ISSUE THREAD

**Issue by Debanitrkl** [harness-community/harness-community.github.io#25]
The following things needs to be added to this repo to increase the  standards of our community profile
- [ ] Description
- [x] Readme
- [ ] Code of Conduct
- [ ] Contributing
- [ ] License
- [ ] Issue templates
- [ ] Pull request template
- [ ] Repository admins accept content reports
